#!/usr/bin/env python3
"""
Generate a switch-case chain that selects lane_bias[k] for k = reg_idx_sub.

fc2_w3x and fc1_w3x preload bias into per-lane registers (BIAS_REG_COUNT
entries = N_DIM/64). Per-subpass we need one specific lane_bias[reg_idx_sub]
where reg_idx_sub is computed from (tn, sp) at runtime. Indexing with
runtime expressions on a register array spills to local memory; the switch
chain forces ptxas to emit a SEL chain over named registers and stays
in-register.

Output is a header fragment meant to be #include'd inside the kernel
function body (where lane_bias / reg_idx_sub / bias_pack are all in
scope). The file lives at gen/bias_switch_inc_<N>.cuh and is built by
the Makefile from this script.

Usage:
    python3 tools/gen_bias_switch.py 48 [-o gen/bias_switch_inc_48.cuh]
    python3 tools/gen_bias_switch.py 12 -o gen/bias_switch_inc_12.cuh

If -o is omitted the chain is written to stdout (legacy behaviour).
"""
import argparse


def emit(n: int) -> str:
    lines = [
        f"/* Auto-generated by tools/gen_bias_switch.py {n}. DO NOT HAND-EDIT. */",
        f"/* Switches reg_idx_sub in [0, {n}) onto lane_bias[reg_idx_sub] without */",
        f"/* spilling to local memory.  Caller provides: lane_bias[], reg_idx_sub, */",
        f"/* bias_pack (lvalue).  Included inside the kernel function body. */",
        "switch (reg_idx_sub) {",
    ]
    for i in range(n - 1):
        lines.append(f"    case {i:2d}: bias_pack = lane_bias[{i:2d}]; break;")
    lines.append(f"    default: bias_pack = lane_bias[{n - 1:2d}]; break;")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("n", type=int, help="BIAS_REG_COUNT (N_DIM / 64)")
    ap.add_argument("-o", "--output", help="output path (default stdout)")
    args = ap.parse_args()
    out = emit(args.n)
    if args.output:
        import os
        os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
        with open(args.output, "w") as f:
            f.write(out)
    else:
        import sys
        sys.stdout.write(out)


if __name__ == "__main__":
    main()
