# SM100a encoding data — auto-generated by sass_edit.py analyze-encoding
# Phase 2+3: Operand Encoding + Control Word Analysis
# Phase 4: Pipe classification, substitution rules, utilization analyzer

import os

# Phase 2.3: Predicate guard encoding
PREDICATE_ENCODING = {
    'enc_mask': 0x000000000000e000,
    'reg_mask': 0x0000000000003000,
    'neg_mask': 0x0000000000008000,
    'enable_mask': 0x0000000000004000,
    'reg_field': (12, 2),
    'neg_field': (15, 1),
    'enable_field': (14, 1),
}

# Phase 2.2: Immediate field encoding
IMMEDIATE_FIELDS = {
    'ATOMS.AND': {
        'type': 'mem_offset',
        'mask': 0x00000c0000000000,
        'fields': [(42, 2)],
    },
    'ATOMS.OR': {
        'type': 'mem_offset',
        'mask': 0x00000021fb0e0c00,
        'fields': [(10, 2), (17, 3), (24, 2), (27, 6), (37, 1)],
    },
    'BAR.SYNC.DEFER_BLOCKING': {
        'type': 'operand_fields',
        'mask': 0x01c2800000000000,
        'fields': [(47, 1), (49, 1), (54, 3)],
    },
    'BRA': {
        'type': 'branch_target',
        'mask': 0xffffffffff000000,
        'fields': [(16, 24)],
        'scale': 4,
        'pc_relative': True,
        'next_pc': True,
    },
    'BRA.DIV': {
        'type': 'branch_target',
        'mask': 0x00000000a5000000,
        'fields': [(24, 1), (26, 1), (29, 1), (31, 1)],
        'pc_relative': True,
    },
    'BRA.U': {
        'type': 'branch_target',
        'mask': 0xfffffffc0ffc0000,
        'fields': [(18, 10), (34, 30)],
        'pc_relative': True,
    },
    'BRA.U.ANY': {
        'type': 'branch_target',
        'mask': 0xfd60b15fffdf4f00,
        'fields': [(8, 4), (14, 1), (16, 5), (22, 15), (38, 1), (40, 1), (44, 2), (47, 1), (53, 2), (56, 1), (58, 6)],
        'pc_relative': True,
    },
    'BSSY': {
        'type': 'branch_target',
        'mask': 0x0001a7f7ffff7c00,
        'fields': [(10, 5), (16, 19), (36, 7), (45, 1), (47, 2)],
        'pc_relative': True,
    },
    'BSSY.RECONVERGENT': {
        'type': 'branch_target',
        'mask': 0xffff000000000000,
        'fields': [(32, 16)],
        'pc_relative': True,
        'next_pc': True,
    },
    'DEPBAR.LE': {
        'type': 'depbar',
        'fields': [(38, 6)],
        'sb_field': (44, 3),
    },
    'LDC': {
        'type': 'mem_offset',
        'mask': 0x0000010000000000,
        'fields': [(40, 1)],
    },
    'LDCU': {
        'type': 'mem_offset',
        'mask': 0x0000028000000000,
        'fields': [(39, 1), (41, 1)],
    },
    'LDS': {
        'type': 'mem_offset',
        'mask': 0x0003f005ff2900c7,
        'fields': [(0, 3), (6, 2), (16, 1), (19, 1), (21, 1), (24, 9), (34, 1), (44, 6)],
    },
    'LDS.128': {
        'type': 'mem_offset',
        'mask': 0x0003f00000000000,
        'fields': [(44, 6)],
        'scale': 16,
    },
    'LDS.64': {
        'type': 'mem_offset',
        'mask': 0x0003000000000000,
        'fields': [(48, 2)],
    },
    'LDTM.16dp256bit.x4': {
        'type': 'mem_offset',
        'mask': 0x0000600000000000,
        'fields': [(45, 2)],
    },
    'LDTM.16dp256bit.x8': {
        'type': 'mem_offset',
        'mask': 0x0000c00000000000,
        'fields': [(46, 2)],
    },
    'LDTM.x16': {
        'type': 'mem_offset',
        'mask': 0x0000300000000000,
        'fields': [(44, 2)],
        'scale': 16,
    },
    'LDTM.x32': {
        'type': 'tmem_offset',
        'fields': [(40, 8)],
    },
    'LDTM.x64': {
        'type': 'mem_offset',
        'mask': 0x0000c00000000000,
        'fields': [(46, 2)],
    },
    'S2R': {
        'type': 'sr_id',
        'mask': 0x0000001f2500010b,
        'fields': [(0, 2), (3, 1), (8, 1), (24, 1), (26, 1), (29, 1), (32, 5)],
    },
    'STS': {
        'type': 'mem_offset',
        'mask': 0x0000f00000000000,
        'fields': [(44, 4)],
    },
    'STS.128': {
        'type': 'mem_offset',
        'mask': 0x00c0000000000000,
        'fields': [(54, 2)],
    },
    'STSM.16.M88.4': {
        'type': 'mem_offset',
        'mask': 0x0060000000000000,
        'fields': [(53, 2)],
    },
    'SYNCS.ARRIVE.TRANS64.A1T0': {
        'type': 'mem_offset',
        'mask': 0x0003f00000000000,
        'fields': [(44, 6)],
        'scale': 16,
    },
    'SYNCS.ARRIVE.TRANS64.RED.A0TR': {
        'type': 'mem_offset',
        'mask': 0x0001f80000000000,
        'fields': [(43, 6)],
        'scale': 8,
    },
    'SYNCS.EXCH.64': {
        'type': 'mem_offset',
        'mask': 0x0281f80000000000,
        'fields': [(43, 6), (55, 1), (57, 1)],
    },
    'SYNCS.PHASECHK.TRANS64': {
        'type': 'mem_offset',
        'mask': 0x0001f0070400f7ab,
        'fields': [(0, 2), (3, 1), (5, 1), (7, 4), (12, 4), (26, 1), (32, 3), (44, 5)],
    },
    'SYNCS.PHASECHK.TRANS64.TRYWAIT': {
        'type': 'mem_offset',
        'mask': 0x0001f00203686ce0,
        'fields': [(5, 3), (10, 2), (13, 2), (19, 1), (21, 2), (24, 2), (33, 1), (44, 5)],
    },
    # --- Manually verified immediate encodings for template families ---
    'HFMA2.BF16_V2': {
        'type': 'constant_pair',
        'mode_bits': 0x800,
        'fields': [(39, 7), (55, 7)],
        'constant_map': {1: 0x7f},
    },
    'IADD3': {
        'type': 'int_imm',
        'mode_bits': 0x800,
        'fields': [(32, 32)],
    },
    'IMAD.MOV.U32': {
        'type': 'int_imm',
        'mode_bits': 0x400,
        'fields': [(32, 32)],
    },
    'IMAD': {
        'type': 'int_imm',
        'mode_bits': 0x800,
        'fields': [(32, 32)],
    },
    'SHF.L.U32': {
        'type': 'int_imm',
        'mode_bits': 0x800,
        'fields': [(32, 5)],
    },
    'MOV': {
        'type': 'int_imm',
        'mode_bits': 0x800,
        'fields': [(32, 32)],
    },
    'ISETP.NE.AND': {
        'type': 'int_imm',
        'mode_bits': 0x200,
        'fields': [(32, 32)],
    },
    'VIADD': {
        'type': 'int_imm',
        'fields': [(32, 8)],
    },
}

# Phase 3.1: Control word field boundaries (SM100a layout)
CONTROL_FIELDS = [(0, 28), (41, 20)]

# Phase 3: SM100a control word sub-field map (verified by barrier correlation analysis)
# Bits [27:5] barrier/scheduling fields:
#   [7:5]   wr_bar     Write barrier SB index (0-6 = SBx, 7 = none)
#   [10:8]  rd_bar     Read barrier SB index (0-6 = SBx, 7 = none)
#   [16:11] wait_mask  Wait barrier bitmask (bit i = wait for SBi)
#   [19:17] pred_dst   Predicate destination index (7 = none/PT)
#   [22:20] rsrc_class Pipeline resource class
#   [25:23] pred_src   Predicate source barrier index (7 = none/PT)
#   [27:26] mem_class  Memory/uniform pipeline class
CTRL_WR_BAR = (5, 3)
CTRL_RD_BAR = (8, 3)
CTRL_WAIT_MASK = (11, 6)
CTRL_PRED_DST = (17, 3)
CTRL_RSRC_CLASS = (20, 3)
CTRL_PRED_SRC = (23, 3)
CTRL_MEM_CLASS = (26, 2)

# Per-family default control words
CONTROL_DEFAULTS = {
    '@!PT': 0x000fe20000000800,
    '@!UPT': 0x000fe4000fffe0ff,
    'ATOMS': 0x0005e8000b000004,
    'BAR': 0x000fe20000010000,
    'BPT': 0x000fea0000300000,
    'BRA': 0x000fea000383ffff,
    'BSSY': 0x000fe20003800000,
    'BSYNC': 0x000fea0003800000,
    'CALL': 0x030fea0003c00000,
    'CCTL': 0x000fe20002000000,
    'CS2R': 0x000fe4000001ff00,
    'DEPBAR': 0x000fe80000000000,
    'ELECT': 0x000fe20003800000,
    'ENDCOLLECTIVE': 0x024ff40003800000,
    'EXIT': 0x002fea0003800000,
    'F2FP': 0x000fe200000010ff,
    'F2I': 0x000f22000020f000,
    'FADD': 0x000fe20000000000,
    'FENCE': 0x004ea20000000000,
    'FFMA': 0x040fe2000000003a,
    'FMUL': 0x008fe20008400000,
    'FSEL': 0x000fe20004000000,
    'FSETP': 0x000fda0003f0d000,
    'HADD2': 0x000fe200000010ff,
    'HFMA2': 0x000fe400000001ff,
    'HMUL2': 0x040fe20000200800,
    'HSETP2': 0x000fea0003f0d802,
    'I2F': 0x000e220008209000,
    'I2FP': 0x000fe20000201000,
    'IABS': 0x000fc60000000000,
    'IADD3': 0x000fe20007ffe0ff,
    'IMAD': 0x000fe200078e00ff,
    'ISETP': 0x000fe20003f05270,
    'LDC': 0x000e700000000a00,
    'LDCU': 0x000e620008000a00,
    'LDG': 0x020368000c1e1900,
    'LDL': 0x002fea0003900000,
    'LDS': 0x000e680008000c00,
    'LDSM': 0x0004680000000200,
    'LDTM': 0x000f240008340000,
    'LEA': 0x000fe4000f8e20ff,
    'LEPC': 0x000fee0000000000,
    'LOP3': 0x000fe200078ec0ff,
    'MEMBAR': 0x0005ec0000008000,
    'MOV': 0x000fe20000000f00,
    'MUFU': 0x001e240000001000,
    'NANOSLEEP': 0x002fea0003900000,
    'NOP': 0x000fe20000000000,
    'P2R': 0x000ff20000000000,
    'PLOP3': 0x000fe20003f4f070,
    'PRMT': 0x000fe40000000000,
    'R2P': 0x040fe20000000000,
    'R2UR': 0x000fe200000e0000,
    'REDUX': 0x000f220000000000,
    'RET': 0x000fea0003c3ffff,
    'RPCMOV': 0x000fcc0000000000,
    'S2R': 0x000ea20000008800,
    'S2UR': 0x000e620000008800,
    'SEL': 0x000fe40000000000,
    'SHF': 0x000fe200000006ff,
    'SHFL': 0x000ea200000e0000,
    'STAS': 0x0005e8000c0008ff,
    'STG': 0x000fe2000c101d06,
    'STL': 0x000fe20000011627,
    'STS': 0x0003e20000000c00,
    'STSM': 0x0003e20000000200,
    'SYNCS': 0x000e6400080011ff,
    'UCGABAR_ARV': 0x008fe20008000000,
    'UCGABAR_WAIT': 0x000fe20008000000,
    'UFLO': 0x000fe200080e0000,
    'UGETNEXTWORKID': 0x000fec0008000100,
    'UIADD3': 0x000fe4000fffe0ff,
    'UIMAD': 0x000fe4000f8e00ff,
    'UISETP': 0x000fc8000bf05270,
    'ULEA': 0x000fe2000f8e18ff,
    'ULOP3': 0x000fe4000f8e3cff,
    'UMOV': 0x000fe20000000000,
    'UP2UR': 0x000fe20008000000,
    'UPLOP3': 0x000fe20003f0f070,
    'UPRMT': 0x000fea0008000009,
    'USEL': 0x000fe40008000000,
    'USHF': 0x000fe400080006ff,
    'UTCATOMSWS': 0x000e640008220800,
    'UTCBAR': 0x0003e600080000ff,
    'UTCQMMA': 0x0007e2000ba0030a,
    'UTMACCTL': 0x0003e40008040000,
    'UTMACMDFLUSH': 0x0001e20000000000,
    'UTMALDG': 0x0003e20008011000,
    'UTMASTG': 0x0005e20008010000,
    'UVIRTCOUNT': 0x000fe20000000000,
    'VIADD': 0x000fe20000000000,
    'VOTEU': 0x000fe20001000000,
    'WARPSYNC': 0x000fea0003800000,
    'YIELD': 0x040fe400078efcff,
}

REUSE_CTRL_MASK = 0x0400000000000000
REUSE_CTRL_BITS = [58]
REUSE_ENC_MASK = 0x000000000000e000
REUSE_ENC_BITS = [13, 14, 15]


# ═══════════════════════════════════════════════════════════════════════════
# Phase 4: Execution pipe classification + substitution rules
#
# Source: bench/calib/instruction_db.py resource classes, validated by
# conflict matrix (data/calib_conflict.txt) and throughput sweep
# (data/calib_tput.txt).
#
# Pipe model (SM100a):
#   ALU    — FP32 + INT share one pipe. FADD, FMUL, FFMA, LOP3, SHF, PRMT,
#            IMAD, SEL, FSEL all contend uniformly (~5.14 cyc/pair in conflict
#            matrix). 2 cyc sustained throughput at ILP≥2.
#   BF16   — Separate pipe: HADD2, HFMA2, HMUL2, F2FP, HSETP2.
#            2 cyc sustained at ILP≥2 (F2FP), 3 cyc at ILP=2 (HADD2/HFMA2).
#   FAST_INT — IADD3, LEA, MOV. Essentially free: IADD3 × anything ≈ max of
#            the two, not sum. 2 cyc standalone, merges pairs (sass_ratio=0.5).
#   MEM    — STS, LDS. Shared SMEM port. 32 cyc STS throughput, 4 cyc LDS.
#   TMA    — UTMASTG, UTMALDG, UTMACMDFLUSH. Separate TMA engine, not LSU.
#   BARRIER — BAR, BSSY, BSYNC, WARPSYNC, MEMBAR, FENCE, DEPBAR, SYNCS.
#            Control flow, not pipelined compute. Not a throughput bottleneck.
#   TMEM   — LDTM (tcgen05.ld). Separate TMEM port, ~25 cyc latency.
#   CONTROL — BRA, EXIT, NOP, CALL, RET, YIELD, ELECT, etc. No pipe cost.
#   SPECIAL — REDUX (44 cyc), VIADD (10 cyc), MUFU, S2R, CS2R. Rare.
# ═══════════════════════════════════════════════════════════════════════════

PIPE_CLASS = {
    # ALU pipe (FP32 + INT, unified — confirmed by conflict matrix)
    'FADD':  'ALU',    'FMUL':  'ALU',    'FFMA':  'ALU',
    'FSEL':  'ALU',    'F2I':   'ALU',    'I2F':   'ALU',
    'LOP3':  'ALU',    'SHF':   'ALU',    'PRMT':  'ALU',
    'IMAD':  'ALU',    'SEL':   'ALU',    'IABS':  'ALU',
    'P2R':   'ALU',    'R2P':   'ALU',
    'ISETP': 'ALU',    'FSETP': 'ALU',
    'UIMAD': 'ALU',    'UISETP': 'ALU',
    'ULOP3': 'ALU',    'USHF':  'ALU',    'UPRMT': 'ALU',
    'USEL':  'ALU',    'UFLO':  'ALU',
    'PLOP3': 'ALU',    'UPLOP3': 'ALU',

    # BF16 pipe (separate from ALU — no cross-contention in conflict matrix)
    'HADD2': 'BF16',   'HFMA2': 'BF16',   'HMUL2': 'BF16',
    'F2FP':  'BF16',   'I2FP':  'BF16',
    'HSETP2': 'BF16',

    # FAST_INT — ~free, doesn't contend with ALU or BF16
    'IADD3': 'FAST_INT',  'LEA':  'FAST_INT',  'MOV':  'FAST_INT',
    'UIADD3': 'FAST_INT', 'ULEA': 'FAST_INT',  'UMOV': 'FAST_INT',

    # Memory (shared SMEM port)
    'STS':  'MEM',   'LDS':  'MEM',
    'STSM': 'MEM',   'LDSM': 'MEM',
    'LDS.64': 'MEM', 'LDS.128': 'MEM',
    'STS.128': 'MEM',

    # Global memory
    'LDG':  'GMEM',  'STG':  'GMEM',
    'LDL':  'GMEM',  'STL':  'GMEM',
    'LDC':  'GMEM',  'LDCU': 'GMEM',
    'ATOMS': 'GMEM',

    # TMA engine (separate from LSU — confirmed by tma_bench)
    'UTMASTG':  'TMA',  'UTMALDG':  'TMA',
    'UTMACMDFLUSH': 'TMA',
    'UTMACCTL': 'TMA',
    'UTCATOMSWS': 'TMA',

    # TMEM loads (separate TMEM port)
    'LDTM': 'TMEM',

    # Barriers / sync (control flow, not throughput-limited)
    'BAR':      'BARRIER',  'WARPSYNC': 'BARRIER',
    'MEMBAR':   'BARRIER',  'FENCE':    'BARRIER',
    'DEPBAR':   'BARRIER',  'SYNCS':    'BARRIER',
    'BSSY':     'BARRIER',  'BSYNC':    'BARRIER',
    'UCGABAR_ARV': 'BARRIER', 'UCGABAR_WAIT': 'BARRIER',
    'UTCBAR':   'BARRIER',

    # Control flow (no pipe cost)
    'BRA':   'CONTROL',  'NOP':    'CONTROL',
    'EXIT':  'CONTROL',  'CALL':   'CONTROL',
    'RET':   'CONTROL',  'YIELD':  'CONTROL',
    'ELECT': 'CONTROL',  'LEPC':   'CONTROL',
    'RPCMOV': 'CONTROL', 'BPT':    'CONTROL',
    'CCTL':  'CONTROL',

    # Special (rare, high latency)
    'REDUX': 'SPECIAL',  'VIADD': 'SPECIAL',
    'MUFU':  'SPECIAL',  'S2R':   'SPECIAL',
    'S2UR':  'SPECIAL',  'CS2R':  'SPECIAL',
    'SHFL':  'SPECIAL',  'R2UR':  'SPECIAL',
    'UP2UR': 'SPECIAL',  'VOTEU': 'SPECIAL',
    'NANOSLEEP': 'SPECIAL',

    # Collective / misc
    'ENDCOLLECTIVE': 'CONTROL',
    'UGETNEXTWORKID': 'CONTROL',
    'UVIRTCOUNT': 'CONTROL',
    'STAS': 'TMA',
    'REDUX': 'SPECIAL',
}

# Throughput in cycles per instruction at the ILP levels seen in real code
# (ILP=2..4 for compute, ILP=1..2 for memory). From data/calib_tput.txt.
PIPE_THROUGHPUT = {
    'ALU':      2,    # FFMA/LOP3/SHF/PRMT/IMAD all ~2.1 cyc at ILP=2
    'BF16':     2,    # F2FP=2.0@ILP=4, HADD2/HFMA2=3.0@ILP=2 (see note)
    'FAST_INT': 0,    # free — overlaps with everything
    'MEM':      32,   # STS.128 = 32 cyc. LDS.128 = 4 cyc but usually paired with STS
    'GMEM':     0,    # fire-and-forget (LDG) or async (STG)
    'TMA':      0,    # async, separate engine
    'TMEM':     0,    # async (LDTM has ~25 cyc latency, hidden by prefetch)
    'BARRIER':  0,    # sync cost, not throughput cost
    'CONTROL':  0,    # no pipe cost
    'SPECIAL':  10,   # VIADD=10, REDUX=44, others variable
}

# BF16 throughput caveat: HADD2/HFMA2 sustain 3.0 cyc/insn at ILP=2,
# only reaching 2.66 cyc at ILP=4. F2FP reaches 2.0 cyc at ILP=4.
# For analysis we use 2 cyc (F2FP-dominated blocks) but flag HADD2/HFMA2
# heavy blocks where the effective throughput is closer to 3 cyc.
BF16_SLOW_FAMILIES = {'HADD2', 'HFMA2', 'HMUL2'}  # 3 cyc at ILP=2


# ═══════════════════════════════════════════════════════════════════════════
# Substitution rules: legal instruction swaps across pipes
#
# These describe HOW to move work between pipes, including the true cost.
# The rebalancer (not yet built) would use these; the analyzer just reports
# what's possible.
#
# Key constraint: BF16 ops are PACKED (2 values per instruction).
# Moving 1 HFMA2 to ALU requires 2 FFMA (scalar FP32), plus conversion
# costs if the data isn't already in FP32.
# ═══════════════════════════════════════════════════════════════════════════

SUBSTITUTIONS = [
    {
        'name': 'HADD2 → 2×FFMA',
        'from_family': 'HADD2',
        'from_pipe': 'BF16',
        'to_family': 'FFMA',
        'to_pipe': 'ALU',
        'expansion': 2,
        #   BF16 packed pair → must unpack to 2 FP32 scalars before FFMA,
        #   then repack 2 FP32 results → BF16 pair afterward.
        #   Unpacking: 2× PRMT (ALU, 2 cyc each) or 2× SHF
        #   Repacking: 1× F2FP (BF16 pipe, 2 cyc) — converts 2 FP32 → 1 BF16x2
        #   Net: saves 1 BF16-pipe slot (HADD2), costs 2 ALU slots (FFMA) +
        #         2 ALU slots (unpack) + 1 BF16 slot (repack F2FP).
        #   IF DATA IS ALREADY FP32 (e.g., right after F2FP output before packing):
        #     saves 1 BF16 slot (HADD2), costs 2 ALU slots (FFMA). No conversion.
        #     But you lose the F2FP that would have packed — net: -1 BF16, +2 ALU.
        'extra_ops_bf16_to_bf16': {
            'ALU': 2,     # 2× PRMT/SHF for unpack (if input is BF16)
            'BF16': 1,    # 1× F2FP for repack (if output must be BF16)
        },
        'extra_ops_fp32_context': {
            'ALU': 0,     # no unpack needed — data already FP32
            'BF16': 0,    # no repack needed — stays in FP32 until final STS
        },
        'notes': (
            'Best when both inputs are already FP32 (e.g., post-F2FP conversion). '
            'If inputs are BF16 pairs, unpack cost (2×ALU + 1×BF16 repack) makes '
            'the swap expensive: net saves 0 BF16 slots and adds 4 ALU slots. '
            'Only profitable when BF16 pipe is >2× overloaded vs ALU.'
        ),
    },
    {
        'name': 'HFMA2 → 2×FFMA',
        'from_family': 'HFMA2',
        'from_pipe': 'BF16',
        'to_family': 'FFMA',
        'to_pipe': 'ALU',
        'expansion': 2,
        'extra_ops_bf16_to_bf16': {
            'ALU': 2,     # unpack BF16 → 2 FP32
            'BF16': 1,    # repack 2 FP32 → BF16x2
        },
        'extra_ops_fp32_context': {
            'ALU': 0,
            'BF16': 0,
        },
        'notes': (
            'Same as HADD2→FFMA. HFMA2.BF16_V2 Rd,Ra,1,1,Rb is multiply-by-1-add, '
            'equivalent to FFMA Rd,Ra,1.0,Rb in FP32. The "×1" disappears in FFMA.'
        ),
    },
    {
        'name': 'F2FP: BF16 pipe, no ALU alternative',
        'from_family': 'F2FP',
        'from_pipe': 'BF16',
        'to_family': None,
        'to_pipe': None,
        'expansion': 0,
        'notes': (
            'F2FP.BF16.F32.PACK_AB converts 2×FP32 → 1×BF16x2. There is no ALU '
            'equivalent — this is a format conversion, not arithmetic. F2FP is '
            'ALWAYS on the BF16 pipe. Any template that outputs BF16 must pay this '
            'cost. The only way to reduce F2FP count is to defer conversion: do all '
            'arithmetic in FP32 and convert only at the final STS boundary.'
        ),
    },
    {
        'name': 'FFMA → HFMA2 (pack 2 scalar FP32 → 1 packed BF16)',
        'from_family': 'FFMA',
        'from_pipe': 'ALU',
        'to_family': 'HFMA2',
        'to_pipe': 'BF16',
        'expansion': 0.5,
        'extra_ops_bf16_to_bf16': {
            'BF16': 0,   # no conversion if both inputs already BF16
            'ALU': 0,
        },
        'extra_ops_fp32_context': {
            'BF16': 2,   # 2× F2FP to convert 4 FP32 inputs → 2 BF16x2
            'ALU': 0,
        },
        'notes': (
            'Only possible when two independent scalar FP32 adds can be paired '
            'into one packed BF16 op. Requires inputs to be in BF16 format or '
            'paying 2× F2FP conversion cost. Precision loss: BF16 has 8-bit '
            'mantissa vs FP32 23-bit. Usually only useful for CUTLASS→our format.'
        ),
    },
]


# ═══════════════════════════════════════════════════════════════════════════
# Pipe analyzer — diagnose utilization imbalance in instruction sequences
# ═══════════════════════════════════════════════════════════════════════════

def classify_instruction(mnemonic):
    """Classify instruction mnemonic → pipe name.

    Strips predicate guards and suffix modifiers to find the base family.
    Returns (pipe, base_family) or ('UNKNOWN', mnemonic) if not found.
    """
    mn = mnemonic
    # Strip predicate guard
    if mn.startswith('@'):
        parts = mn.split(None, 1)
        mn = parts[1] if len(parts) > 1 else mn

    # Try exact match first (handles dotted names like STS.128)
    if mn in PIPE_CLASS:
        return PIPE_CLASS[mn], mn

    # Try base family (before first dot)
    base = mn.split('.')[0]
    if base in PIPE_CLASS:
        return PIPE_CLASS[base], base

    return 'UNKNOWN', mn


def analyze_pipes(instructions, title='Template', verbose=True):
    """Analyze pipe utilization of an instruction sequence.

    instructions: list of (mnemonic, count) tuples, or list of mnemonic strings.
    Returns a dict with analysis results.

    Prints a detailed diagnostic if verbose=True.
    """
    # Normalize input
    if instructions and isinstance(instructions[0], str):
        # Count occurrences
        from collections import Counter
        raw_counts = Counter()
        for mn in instructions:
            mn = mn.strip()
            if not mn or mn.startswith('#') or mn.startswith('.'):
                continue
            if mn.startswith('@'):
                parts = mn.split(None, 1)
                mn = parts[1] if len(parts) > 1 else mn
            base = mn.split()[0]
            raw_counts[base] += 1
        instructions = list(raw_counts.items())

    # Classify each instruction
    pipe_ops = {}      # pipe → total op count
    pipe_detail = {}   # pipe → {family: count}
    bf16_slow_count = 0
    total_insns = 0
    unknowns = []

    for mnemonic, count in instructions:
        pipe, family = classify_instruction(mnemonic)
        total_insns += count

        if pipe == 'UNKNOWN':
            unknowns.append((mnemonic, count))
            continue

        pipe_ops[pipe] = pipe_ops.get(pipe, 0) + count
        if pipe not in pipe_detail:
            pipe_detail[pipe] = {}
        pipe_detail[pipe][family] = pipe_detail[pipe].get(family, 0) + count

        if family in BF16_SLOW_FAMILIES:
            bf16_slow_count += count

    # Compute cycles per pipe
    pipe_cycles = {}
    for pipe, count in pipe_ops.items():
        tput = PIPE_THROUGHPUT.get(pipe, 0)
        pipe_cycles[pipe] = count * tput

    # BF16 effective throughput adjustment
    bf16_total = pipe_ops.get('BF16', 0)
    bf16_cycles_adjusted = 0
    if bf16_total > 0:
        bf16_fast = bf16_total - bf16_slow_count  # F2FP etc.
        bf16_cycles_adjusted = bf16_fast * 2 + bf16_slow_count * 3
        # Use the worse estimate (conservative)
        pipe_cycles['BF16'] = max(pipe_cycles.get('BF16', 0), bf16_cycles_adjusted)

    # Find bottleneck among compute pipes (ALU, BF16) and memory pipes separately
    # MEM (STS/LDS) is scheduling-dependent: STS throughput = 32 cyc back-to-back,
    # but each STS can shadow up to ~4 BF16/ALU ops (effectively free work).
    # In an interleaved schedule, MEM rarely dominates. Report it separately.
    compute_only = {p: c for p, c in pipe_cycles.items() if p in ('ALU', 'BF16')}
    all_nonzero = {p: c for p, c in pipe_cycles.items() if c > 0}

    if compute_only:
        compute_bottleneck = max(compute_only, key=compute_only.get)
        compute_bottleneck_cyc = compute_only[compute_bottleneck]
    else:
        compute_bottleneck = None
        compute_bottleneck_cyc = 0

    if all_nonzero:
        bottleneck_pipe = max(all_nonzero, key=all_nonzero.get)
        bottleneck_cycles = all_nonzero[bottleneck_pipe]
    else:
        bottleneck_pipe = None
        bottleneck_cycles = 0

    # Substitution analysis (based on compute bottleneck, not MEM)
    sub_analysis = []
    if compute_bottleneck in ('BF16', 'ALU'):
        target_pipe = 'ALU' if compute_bottleneck == 'BF16' else 'BF16'
        for sub in SUBSTITUTIONS:
            if sub['from_pipe'] != compute_bottleneck:
                continue
            if sub['to_pipe'] is None:
                sub_analysis.append({
                    'rule': sub['name'],
                    'movable_count': pipe_detail.get(compute_bottleneck, {}).get(sub['from_family'], 0),
                    'expansion': sub['expansion'],
                    'notes': sub['notes'],
                    'blocked': True,
                })
                continue
            movable = pipe_detail.get(compute_bottleneck, {}).get(sub['from_family'], 0)
            if movable == 0:
                continue
            sub_analysis.append({
                'rule': sub['name'],
                'movable_count': movable,
                'expansion': sub['expansion'],
                'target_pipe': target_pipe,
                'extra_ops': sub.get('extra_ops_fp32_context', {}),
                'notes': sub['notes'],
                'blocked': False,
            })

    # Balance computation (what if we moved N ops?)
    balance_info = None
    if compute_bottleneck == 'BF16' and 'ALU' in pipe_cycles:
        alu_cyc = pipe_cycles['ALU']
        bf16_cyc = pipe_cycles['BF16']
        # Movable: HADD2 + HFMA2 (not F2FP — locked to BF16)
        movable_bf16 = sum(
            pipe_detail.get('BF16', {}).get(f, 0)
            for f in ('HADD2', 'HFMA2', 'HMUL2')
        )
        if movable_bf16 > 0:
            # Each moved op: -1 BF16 slot (saves tput cyc), +2 ALU slots (expansion)
            # In FP32 context (no unpack/repack): -2 BF16 cyc, +4 ALU cyc
            # With BF16 pack/unpack: -2 BF16 cyc + 2 repack, +4 ALU + 4 unpack
            # Best case: FP32 context
            # BF16 effective tput for HADD2/HFMA2 = 3 cyc
            # Solve: (bf16_cyc - 3*N) = (alu_cyc + 2*2*N) for balance
            #   bf16_cyc - 3N = alu_cyc + 4N  →  N = (bf16_cyc - alu_cyc) / 7
            # But this assumes FP32 context. With BF16 context add repack cost.
            N_fp32 = (bf16_cyc - alu_cyc) / 7.0
            N_fp32 = max(0, min(movable_bf16, int(N_fp32)))
            new_bf16 = bf16_cyc - N_fp32 * 3
            new_alu = alu_cyc + N_fp32 * 2 * 2
            balance_info = {
                'movable_ops': movable_bf16,
                'optimal_N_fp32_context': N_fp32,
                'current_bf16_cyc': bf16_cyc,
                'current_alu_cyc': alu_cyc,
                'balanced_bf16_cyc': new_bf16,
                'balanced_alu_cyc': new_alu,
                'savings_pct': (1 - max(new_bf16, new_alu) / bf16_cyc) * 100,
            }

    elif compute_bottleneck == 'ALU' and 'BF16' in pipe_cycles:
        alu_cyc = pipe_cycles['ALU']
        bf16_cyc = pipe_cycles['BF16']
        movable_alu = sum(
            pipe_detail.get('ALU', {}).get(f, 0)
            for f in ('FFMA', 'FADD', 'FMUL')
        )
        if movable_alu > 0:
            # 2 FFMA → 1 HFMA2: saves 2 ALU slots, costs 1 BF16 slot
            # But need pairs. And may need F2FP conversion.
            N_alu = (alu_cyc - bf16_cyc) / 6.0  # 2*2 saved ALU + 1*2 added BF16
            N_alu = max(0, min(movable_alu // 2, int(N_alu)))
            new_alu = alu_cyc - N_alu * 2 * 2
            new_bf16 = bf16_cyc + N_alu * 2
            balance_info = {
                'movable_ops': movable_alu,
                'optimal_N_pairs': N_alu,
                'current_alu_cyc': alu_cyc,
                'current_bf16_cyc': bf16_cyc,
                'balanced_alu_cyc': new_alu,
                'balanced_bf16_cyc': new_bf16,
                'savings_pct': (1 - max(new_bf16, new_alu) / alu_cyc) * 100,
            }

    result = {
        'total_insns': total_insns,
        'pipe_ops': pipe_ops,
        'pipe_detail': pipe_detail,
        'pipe_cycles': pipe_cycles,
        'bottleneck_pipe': bottleneck_pipe,
        'bottleneck_cycles': bottleneck_cycles,
        'compute_bottleneck': compute_bottleneck,
        'compute_bottleneck_cyc': compute_bottleneck_cyc,
        'bf16_slow_count': bf16_slow_count,
        'substitutions': sub_analysis,
        'balance': balance_info,
        'unknowns': unknowns,
    }

    if verbose:
        _print_analysis(result, title)

    return result


def _print_analysis(r, title):
    """Print formatted pipe analysis diagnostic."""
    print(f'\n{"=" * 70}')
    print(f'  PIPE UTILIZATION ANALYSIS: {title}')
    print(f'  {r["total_insns"]} instructions total')
    print(f'{"=" * 70}')

    # Pipe breakdown
    max_cyc = max(r['pipe_cycles'].values()) if r['pipe_cycles'] else 1
    pipe_order = ['BF16', 'ALU', 'MEM', 'GMEM', 'TMA', 'TMEM',
                  'BARRIER', 'CONTROL', 'FAST_INT', 'SPECIAL']

    # Use compute bottleneck for bar scaling (MEM is scheduling-dependent)
    compute_max = max(
        (r['pipe_cycles'].get(p, 0) for p in ('BF16', 'ALU', 'MEM')),
        default=1
    )
    if compute_max == 0:
        compute_max = max_cyc if max_cyc > 0 else 1

    print(f'\n  {"Pipe":<12} {"Ops":>5} {"Cyc":>6} {"Tput":>5}  Utilization')
    print(f'  {"─" * 55}')

    for pipe in pipe_order:
        if pipe not in r['pipe_ops']:
            continue
        ops = r['pipe_ops'][pipe]
        cyc = r['pipe_cycles'].get(pipe, 0)
        tput = PIPE_THROUGHPUT.get(pipe, 0)
        bar_len = int(30 * cyc / compute_max) if compute_max > 0 else 0
        bar = '█' * bar_len
        if pipe == r['compute_bottleneck']:
            marker = ' ◄ COMPUTE BOTTLENECK'
        elif pipe == r['bottleneck_pipe'] and pipe != r['compute_bottleneck']:
            marker = ' (scheduling-dependent)'
        else:
            marker = ''
        tput_str = f'{tput}c' if tput > 0 else 'free'
        print(f'  {pipe:<12} {ops:>5} {cyc:>6} {tput_str:>5}  {bar}{marker}')

    # MEM caveat
    mem_ops = r['pipe_ops'].get('MEM', 0)
    if mem_ops > 0:
        sts_count = r['pipe_detail'].get('MEM', {}).get('STS', 0) + \
                    r['pipe_detail'].get('MEM', {}).get('STS.128', 0)
        if sts_count > 0:
            print(f'\n  ℹ  MEM cycle count assumes back-to-back STS ({sts_count}× STS.128 '
                  f'× 32 cyc = {sts_count * 32} cyc).')
            print(f'     In practice, each STS shadows ~4 free compute ops. With good')
            print(f'     scheduling (interleaved STS), effective MEM cost is much lower.')
            print(f'     Compute pipe balance matters more than raw MEM throughput.')

    # Detail breakdown for compute pipes
    for pipe in ('BF16', 'ALU', 'MEM'):
        if pipe in r['pipe_detail'] and len(r['pipe_detail'][pipe]) > 1:
            print(f'\n  {pipe} detail:')
            for fam, cnt in sorted(r['pipe_detail'][pipe].items(),
                                   key=lambda x: -x[1]):
                slow = ' (3 cyc @ ILP=2)' if fam in BF16_SLOW_FAMILIES else ''
                print(f'    {fam:<20} {cnt:>4}{slow}')

    # BF16 throughput warning
    if r['bf16_slow_count'] > 0:
        bf16_total = r['pipe_ops'].get('BF16', 0)
        pct = r['bf16_slow_count'] / bf16_total * 100 if bf16_total else 0
        print(f'\n  ⚠  BF16 throughput warning: {r["bf16_slow_count"]}/{bf16_total} '
              f'ops ({pct:.0f}%) are HADD2/HFMA2 (3 cyc @ ILP=2, not 2 cyc).')
        print(f'     Effective BF16 critical path ≈ {r["pipe_cycles"].get("BF16", 0)} cyc '
              f'(not {bf16_total * 2} cyc).')

    # Unknowns
    if r['unknowns']:
        print(f'\n  ⚠  Unclassified instructions:')
        for mn, cnt in r['unknowns']:
            print(f'    {mn:<20} {cnt:>4}')

    # Substitution analysis
    if r['substitutions']:
        print(f'\n  SUBSTITUTION OPPORTUNITIES')
        print(f'  {"─" * 55}')
        for sub in r['substitutions']:
            if sub['blocked']:
                print(f'  ✗ {sub["rule"]}: {sub["movable_count"]} ops — NOT SUBSTITUTABLE')
                print(f'    {sub["notes"][:100]}')
            else:
                exp = sub['expansion']
                n = sub['movable_count']
                print(f'  → {sub["rule"]}: {n} ops available (1:{exp} expansion)')
                if sub.get('extra_ops'):
                    extras = ', '.join(f'+{v} {k}' for k, v in sub['extra_ops'].items() if v)
                    if extras:
                        print(f'    Conversion overhead per swap: {extras}')
                # Truncate notes sensibly
                notes = sub['notes']
                if len(notes) > 120:
                    notes = notes[:117] + '...'
                print(f'    {notes}')

    # Balance recommendation
    bal = r['balance']
    if bal:
        print(f'\n  BALANCE RECOMMENDATION')
        print(f'  {"─" * 55}')
        if 'optimal_N_fp32_context' in bal:
            N = bal['optimal_N_fp32_context']
            print(f'  Move {N} of {bal["movable_ops"]} substitutable ops from '
                  f'BF16 → ALU:')
            print(f'    BF16: {bal["current_bf16_cyc"]:>4} cyc → {bal["balanced_bf16_cyc"]:>4} cyc')
            print(f'    ALU:  {bal["current_alu_cyc"]:>4} cyc → {bal["balanced_alu_cyc"]:>4} cyc')
            print(f'    Critical path reduction: {bal["savings_pct"]:.1f}%')
            print()
            print(f'  ⚠  CONVERSION COSTS — these estimates assume FP32 context:')
            print(f'     Best case: data is already FP32 (e.g., bias+residual applied')
            print(f'     AFTER F2FP but BEFORE final packing). Only 2×FFMA per op.')
            print(f'     Worst case: data in BF16 pairs. Each swap costs +2 ALU (unpack)')
            print(f'     + 1 BF16 (F2FP repack), nearly eliminating the savings.')
            print(f'     The key: restructure the computation order so bias+residual')
            print(f'     addition happens in FP32 BEFORE the BF16 conversion step.')
        elif 'optimal_N_pairs' in bal:
            N = bal['optimal_N_pairs']
            print(f'  Move {N} FFMA pairs from ALU → BF16 (as {N} HFMA2):')
            print(f'    ALU:  {bal["current_alu_cyc"]:>4} cyc → {bal["balanced_alu_cyc"]:>4} cyc')
            print(f'    BF16: {bal["current_bf16_cyc"]:>4} cyc → {bal["balanced_bf16_cyc"]:>4} cyc')
            print(f'    Critical path reduction: {bal["savings_pct"]:.1f}%')
            print()
            print(f'  ⚠  Requires pairable scalar FP32 ops (independent lo/hi halves)')
            print(f'     and BF16 precision is acceptable (8-bit vs 23-bit mantissa).')

    if not r['substitutions'] and not bal:
        cb = r['compute_bottleneck']
        if cb is None or r['compute_bottleneck_cyc'] == 0:
            print(f'\n  No significant compute work. Bottleneck is '
                  f'{r["bottleneck_pipe"] or "none"}.')
        else:
            ratio = 0
            other = 'ALU' if cb == 'BF16' else 'BF16'
            other_cyc = r['pipe_cycles'].get(other, 0)
            if other_cyc > 0:
                ratio = r['compute_bottleneck_cyc'] / other_cyc
            print(f'\n  Compute pipes: {cb} = {r["compute_bottleneck_cyc"]} cyc, '
                  f'{other} = {other_cyc} cyc (ratio {ratio:.1f}:1).')
            if ratio < 1.5:
                print(f'  Pipes are reasonably balanced. No substitutions recommended.')
            else:
                print(f'  {cb} is {ratio:.1f}× overloaded vs {other}, but no '
                      f'substitutable ops found on the bottleneck pipe.')

    print()


def analyze_template_file(path, title=None):
    """Analyze a .s template file's pipe utilization.

    Reads the file, extracts instruction mnemonics, runs analyze_pipes.
    """
    if title is None:
        title = os.path.basename(path)

    with open(path) as f:
        lines = f.readlines()

    mnemonics = []
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith('#') or stripped.startswith('.'):
            continue
        mnemonics.append(stripped)

    return analyze_pipes(mnemonics, title=title)


# CLI entry point for standalone analysis
if __name__ == '__main__':
    import sys
    if len(sys.argv) < 2:
        print('Usage: python3 sm100a_encoding.py <template.s> [title]')
        print('       python3 sm100a_encoding.py --compare <a.s> <b.s>')
        sys.exit(1)

    if sys.argv[1] == '--compare' and len(sys.argv) >= 4:
        r1 = analyze_template_file(sys.argv[2])
        r2 = analyze_template_file(sys.argv[3])
        # Print side-by-side bottleneck comparison
        print(f'\n{"=" * 70}')
        print(f'  COMPARISON (compute pipes only)')
        print(f'{"=" * 70}')
        n1 = os.path.basename(sys.argv[2])
        n2 = os.path.basename(sys.argv[3])
        cb1 = r1['compute_bottleneck']
        cb2 = r2['compute_bottleneck']
        cc1 = r1['compute_bottleneck_cyc']
        cc2 = r2['compute_bottleneck_cyc']
        print(f'  {n1:<30} compute bottleneck: {cb1} = {cc1} cyc')
        print(f'  {n2:<30} compute bottleneck: {cb2} = {cc2} cyc')

        # Per-pipe comparison
        for p in ('BF16', 'ALU'):
            c1p = r1['pipe_cycles'].get(p, 0)
            c2p = r2['pipe_cycles'].get(p, 0)
            if c1p or c2p:
                print(f'    {p:<8} {c1p:>6} cyc vs {c2p:>6} cyc')

        # Note: templates cover different col ranges, so normalize per-col
        t1 = r1['total_insns']
        t2 = r2['total_insns']
        if t1 != t2:
            print(f'\n  ℹ  Templates cover different scope ({t1} vs {t2} insns).')
            print(f'     Pipe ratios matter more than absolute cycle counts.')

        # Compute pipe ratio (BF16:ALU imbalance) — the actionable metric
        for name, r in [(n1, r1), (n2, r2)]:
            bf16 = r['pipe_cycles'].get('BF16', 0)
            alu = r['pipe_cycles'].get('ALU', 0)
            if bf16 > 0 and alu > 0:
                ratio = bf16 / alu
                print(f'  {name:<30} BF16:ALU ratio = {ratio:.1f}:1')
            elif bf16 > 0:
                print(f'  {name:<30} BF16:ALU ratio = ∞ (no ALU compute)')
        print()
    else:
        title = sys.argv[2] if len(sys.argv) > 2 else None
        analyze_template_file(sys.argv[1], title=title)
